### ISSUE TITLE
base64 encoded Photos

### ISSUE THREAD

**Issue by avenjamin** [Astrotomic/laravel-vcard#13]
I'm seeing an issue with base64 encoded images and wondered if we can improve the Photo property class.

https://github.com/Astrotomic/laravel-vcard/blob/0ad87fe98a538c6b3d9232ac7dfc65984bb976f5/src/Properties/Photo.php#L13

In my testing with Apple Contacts on both iOS and macOS the photo only appears if the photo is written with:

`PHOTO;ENCODING=b;TYPE=JPEG:<base64_encoded_image_without_newlines>`

eg

`PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZJRgAB…`

Notice also that `PHOTO:` is now `PHOTO;` (i.e. a semicolon instead)

Ideally i'd like to have a flag to mark $this->photo as a file path or as a base64 encoded string unless we can detect this somehow?

If it's a file path then we can use `base64encode` on the file.

Thoughts?

**Comment by Gummibeer** [comment]
Hey, what happens if someone uses a PNG, BMP, GIF whatever image file? 🤔

**Comment by Gummibeer** [comment]
And right now the library only creates v4.0 vCards. Your suggested change is v3.0 - so it would need a different version support change in the package.

3.0: PHOTO;TYPE=JPEG:http://example.org/photo.jpg
3.0: PHOTO;TYPE=JPEG;ENCODING=b:[base64-data]
4.0: PHOTO;MEDIATYPE=image/jpeg:http://example.org/photo.jpg
4.0: PHOTO:data:image/jpeg;base64,[base64-data]

**Comment by avenjamin** [comment]
Ah ok.

Regarding the image format it looks like it's possible to detect it when decoding the base64 data.
See here: https://stackoverflow.com/questions/6061505/detecting-image-type-from-base64-string-in-php

I'm not 100% sure, but it looks like support for version 4 isn't quite there in Apple Contacts.
Off topic, when setting the type for `TEL` e.g. `TEL;type=work:+1234` if the vCard is version 4, the type isn't picked up.
If I manually edit the vCard version to 3, then it does parse the type and sets the telephone type to `work`.

Clearly we working with a standard that's not being implemented quite right by venders - Or I'm missing something which is more likely 😝

**Comment by Gummibeer** [comment]
Yeah, it's definitely on the roadmap to implement the different version support thing. Like Ramsey UUID package for example.

**Comment by Wefabric-Kevin** [comment]
Hi there, I'd like to add to this issue that I've also ran into the problem that the photo isn't imported when importing a VCard into Apple Contacts (Version 2498.5).

Specifically in this line:
https://github.com/Astrotomic/laravel-vcard/blob/0ad87fe98a538c6b3d9232ac7dfc65984bb976f5/src/Properties/Photo.php#L13

Where it is written as `PHOTO:` (colon) instead of `PHOTO;` (semicolon).
[Wikipedia > Vcard](https://en.wikipedia.org/wiki/VCard) > PHOTO also lists the semicolon as used in every version.

If I call the vcard with: 
```
return \Astrotomic\Vcard\Vcard::make()
// the rest of the arguments
->photo('ENCODING=BASE64;TYPE=JPEG:'.base64_encode(Storage::disk('photos')->get($employee->photo_small)))
```
It exports the Vcard as:

```
BEGIN:VCARD
VERSION:4.0
// THE REST OF THE ARGUMENTS
PHOTO:ENCODING=BASE64;TYPE=JPEG:iVBORw0KGgoAAAANSUhEUgAAAQMAAABjCAIAAAAQMPJyAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYW SHORTENED
REV:2023-06-19T06:41:32.605454Z
PRODID:-//Astrotomic vCard
END:VCARD
```

If I manually change the colon to a semicolon I can then succesfully import the photo.

**Comment by avenjamin** [comment]
Thats exactly what I found too - I've manually tweaked my version of the code, but need to look at committing back to the repo.

**Comment by Wefabric-Kevin** [comment]
@Gummibeer & @avenjamin I've created a pull-request for this exact change for the Photo property.
